/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_trial;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Add_equipment extends javax.swing.JFrame {

    /**
     * Creates new form Add_equipment
     */
    public Connection database;
    public Add_equipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        qn = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        prb = new javax.swing.JTextField();
        ser = new javax.swing.JTextField();
        clr = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Equipment");
        setBounds(new java.awt.Rectangle(830, 270, 420, 360));
        setMinimumSize(new java.awt.Dimension(420, 360));
        setPreferredSize(new java.awt.Dimension(420, 360));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipment name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Condition");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 66, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 66, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Problem");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Servicing");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        name.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 160, -1));

        qn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(qn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, -1));

        con.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, -1));

        prb.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(prb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, -1));

        ser.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, -1));

        clr.setBackground(new java.awt.Color(255, 0, 0));
        clr.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        clr.setText("Clear");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });
        getContentPane().add(clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 280, 90, -1));

        sub.setBackground(new java.awt.Color(153, 255, 153));
        sub.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        sub.setText("Submit");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 90, -1));

        jLabel6.setBackground(new java.awt.Color(153, 255, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/430X360(bg).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
         String ename = name.getText();
        String quantity = qn.getText();
        String condition = con.getText();
        String problem = prb.getText();
        String service = ser.getText();
      

        try {

            if (ename.equals("") || quantity.equals("") || condition.equals("") || problem.equals("") || service.equals("") ) {
                JOptionPane.showMessageDialog(null, "Opps!! Try Again", "Warning", JOptionPane.ERROR_MESSAGE);
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection databse = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
                String sql = "insert into equipment (name,amount,state,problem,service) values (?,?,?,?,?)";
                PreparedStatement p = (PreparedStatement) databse.prepareStatement(sql);
                p.setString(1, ename);
                p.setString(2, quantity);
                p.setString(3, condition);
                p.setString(4,problem );
                p.setString(5,service);
         
                    p.executeUpdate();
                    dispose();
                    databse.close();
                    JOptionPane.showMessageDialog(null, "Successfully Submitted", "Welcome", JOptionPane.PLAIN_MESSAGE);
                
               
                
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_subActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        name.setText("");
        qn.setText("");
        con.setText("");
        prb.setText("");
        ser.setText("");
        
    }//GEN-LAST:event_clrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_equipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr;
    private javax.swing.JTextField con;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField prb;
    private javax.swing.JTextField qn;
    private javax.swing.JTextField ser;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
