/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_trial;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Choose1 extends javax.swing.JFrame {

    /**
     * Creates new form Choose1
     */
    public Choose1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Log_btn = new javax.swing.JButton();
        reg_btn = new javax.swing.JButton();
        pack_btn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kazi Gym Desk");
        setBounds(new java.awt.Rectangle(300, 150, 700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Log_btn.setBackground(new java.awt.Color(0, 0, 0));
        Log_btn.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        Log_btn.setForeground(new java.awt.Color(255, 0, 0));
        Log_btn.setText("Login");
        Log_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_btnMouseExited(evt);
            }
        });
        Log_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Log_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 220, 70));

        reg_btn.setBackground(new java.awt.Color(0, 0, 0));
        reg_btn.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        reg_btn.setForeground(new java.awt.Color(255, 0, 0));
        reg_btn.setText("Register");
        reg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_btnMouseExited(evt);
            }
        });
        reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 220, 70));

        pack_btn.setBackground(new java.awt.Color(0, 0, 0));
        pack_btn.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        pack_btn.setForeground(new java.awt.Color(255, 0, 0));
        pack_btn.setText("Package");
        pack_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pack_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pack_btnMouseExited(evt);
            }
        });
        pack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pack_btnActionPerformed(evt);
            }
        });
        getContentPane().add(pack_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 220, 70));

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/bg2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pack_btnActionPerformed
        Package pack = new Package();
        pack.setVisible(true);
        dispose();
    }//GEN-LAST:event_pack_btnActionPerformed

    private void Log_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_btnActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_Log_btnActionPerformed

    private void reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnActionPerformed
        RegLog rg = new RegLog();
        rg.setVisible(true);
        dispose();
    }//GEN-LAST:event_reg_btnActionPerformed

    private void Log_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_btnMouseEntered
        Log_btn.setForeground(Color.WHITE);
    }//GEN-LAST:event_Log_btnMouseEntered

    private void Log_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_btnMouseExited
        Log_btn.setForeground(Color.red);
    }//GEN-LAST:event_Log_btnMouseExited

    private void reg_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseEntered
        reg_btn.setForeground(Color.WHITE);
    }//GEN-LAST:event_reg_btnMouseEntered

    private void reg_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseExited
        reg_btn.setForeground(Color.red);
    }//GEN-LAST:event_reg_btnMouseExited

    private void pack_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pack_btnMouseEntered
        pack_btn.setForeground(Color.WHITE);

    }//GEN-LAST:event_pack_btnMouseEntered

    private void pack_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pack_btnMouseExited
        pack_btn.setForeground(Color.red);
    }//GEN-LAST:event_pack_btnMouseExited

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame frame = new JFrame() ;
        int result = JOptionPane.showConfirmDialog(frame,
            "Are You Sure You Want to Quit ?", "Quit : ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
         System.exit(0);
        else if (result == JOptionPane.NO_OPTION)
          frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
         exit.setForeground(Color.red);
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_btn;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pack_btn;
    private javax.swing.JButton reg_btn;
    // End of variables declaration//GEN-END:variables
}
