/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_trial;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author MN
 */
public class MemberMain extends javax.swing.JFrame {

    /**
     * Creates new form MemberMain
     */
    public MemberMain() {
        initComponents();
    }
    public Connection database;
    int button = 0;
    int flag = 0;
    
    private void updateTable() {
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
            
            String sql = "select Jan,Feb,Mar,April,May,June,July,Aug,Sept,Oct, Nov,Decm  from member_info where id=?";
            PreparedStatement p = database.prepareStatement(sql);
            p.setString(1, mw_id.getText());
            ResultSet ans = p.executeQuery();
            mweight.setModel(DbUtils.resultSetToTableModel(ans));
            ans.close();
            p.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        bg = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        usermm = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        l_name = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        pic = new javax.swing.JLabel();
        show_pro_mem = new javax.swing.JButton();
        log_out_mem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        g_id = new javax.swing.JTextField();
        show_paa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mw_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mw_jan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mw_feb = new javax.swing.JTextField();
        mw_mar = new javax.swing.JTextField();
        mw_ap = new javax.swing.JTextField();
        mw_may = new javax.swing.JTextField();
        mw_jun = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mw_jul = new javax.swing.JTextField();
        mw_aug = new javax.swing.JTextField();
        mw_sep = new javax.swing.JTextField();
        mw_oct = new javax.swing.JTextField();
        mw_nov = new javax.swing.JTextField();
        mw_dec = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mweight = new javax.swing.JTable();
        mw_clr = new javax.swing.JButton();
        mw_up_btn = new javax.swing.JButton();
        mw_show_btn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        log___out = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Desk");
        setBounds(new java.awt.Rectangle(100, 20, 1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("First Name");
        jLabel30.setToolTipText("");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Age");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Height(cm)");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Blood Group");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Email");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        email.setEditable(false);
        email.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 210, 40));

        bg.setEditable(false);
        bg.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bg.setToolTipText("");
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgMouseExited(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, 40));

        height.setEditable(false);
        height.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        height.setToolTipText("");
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, 40));

        age.setEditable(false);
        age.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, 40));

        f_name.setEditable(false);
        f_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 200, 40));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 107, 31));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText(" Gender (M/F)");
        jLabel36.setToolTipText("");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Weight(kg)");
        jLabel37.setToolTipText("");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Mobile");
        jLabel38.setToolTipText("");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 80, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("NID");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("UserName");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        usermm.setEditable(false);
        usermm.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        usermm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usermmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usermmMouseExited(evt);
            }
        });
        usermm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermmActionPerformed(evt);
            }
        });
        jPanel1.add(usermm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 200, 30));

        nid.setEditable(false);
        nid.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nidMouseExited(evt);
            }
        });
        jPanel1.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 200, 40));

        mobile.setEditable(false);
        mobile.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mobileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobileMouseExited(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 200, 40));

        weight.setEditable(false);
        weight.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 200, 40));

        gender.setEditable(false);
        gender.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 200, 40));

        l_name.setEditable(false);
        l_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameActionPerformed(evt);
            }
        });
        jPanel1.add(l_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 200, 40));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Password");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        pass.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passMouseExited(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 220, -1));

        pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 250, 240));

        show_pro_mem.setBackground(new java.awt.Color(0, 0, 0));
        show_pro_mem.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        show_pro_mem.setForeground(new java.awt.Color(204, 255, 204));
        show_pro_mem.setText("Show Profile");
        show_pro_mem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show_pro_memMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                show_pro_memMouseExited(evt);
            }
        });
        show_pro_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pro_memActionPerformed(evt);
            }
        });
        jPanel1.add(show_pro_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, -1, -1));

        log_out_mem.setBackground(new java.awt.Color(0, 0, 0));
        log_out_mem.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log_out_mem.setForeground(new java.awt.Color(255, 255, 204));
        log_out_mem.setText("Log Out");
        log_out_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_memActionPerformed(evt);
            }
        });
        jPanel1.add(log_out_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 429, 80, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gym ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        g_id.setEditable(false);
        g_id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel1.add(g_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 210, -1));

        show_paa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        show_paa.setForeground(new java.awt.Color(255, 0, 51));
        show_paa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(show_paa, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 230, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/table.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Profile", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        mw_id.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mw_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_idActionPerformed(evt);
            }
        });
        jPanel3.add(mw_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("January");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        mw_jan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mw_jan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_janActionPerformed(evt);
            }
        });
        jPanel3.add(mw_jan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("February");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("March");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("April");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("May");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("June");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        mw_feb.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_feb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));

        mw_mar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_mar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, -1));

        mw_ap.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 110, -1));

        mw_may.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_may, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, -1));

        mw_jun.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_jun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("July");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("August");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("September");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("October");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("November");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("December");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        mw_jul.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_jul, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 100, -1));

        mw_aug.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_aug, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, -1));

        mw_sep.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 100, -1));

        mw_oct.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_oct, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        mw_nov.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_nov, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 100, -1));

        mw_dec.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel3.add(mw_dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 100, 40));

        mweight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jan", "Feb", "Mar", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Decm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mweight);
        if (mweight.getColumnModel().getColumnCount() > 0) {
            mweight.getColumnModel().getColumn(0).setResizable(false);
            mweight.getColumnModel().getColumn(1).setResizable(false);
            mweight.getColumnModel().getColumn(2).setResizable(false);
            mweight.getColumnModel().getColumn(3).setResizable(false);
            mweight.getColumnModel().getColumn(4).setResizable(false);
            mweight.getColumnModel().getColumn(5).setResizable(false);
            mweight.getColumnModel().getColumn(6).setResizable(false);
            mweight.getColumnModel().getColumn(7).setResizable(false);
            mweight.getColumnModel().getColumn(8).setResizable(false);
            mweight.getColumnModel().getColumn(9).setResizable(false);
            mweight.getColumnModel().getColumn(10).setResizable(false);
            mweight.getColumnModel().getColumn(11).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 600, 80));

        mw_clr.setBackground(new java.awt.Color(0, 0, 0));
        mw_clr.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mw_clr.setForeground(new java.awt.Color(255, 0, 0));
        mw_clr.setText("Clear");
        mw_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_clrActionPerformed(evt);
            }
        });
        jPanel3.add(mw_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 90, 40));

        mw_up_btn.setBackground(new java.awt.Color(0, 0, 0));
        mw_up_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mw_up_btn.setForeground(new java.awt.Color(204, 204, 255));
        mw_up_btn.setText("Update");
        mw_up_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_up_btnActionPerformed(evt);
            }
        });
        jPanel3.add(mw_up_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, 40));

        mw_show_btn.setBackground(new java.awt.Color(0, 0, 0));
        mw_show_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mw_show_btn.setForeground(new java.awt.Color(255, 153, 255));
        mw_show_btn.setText("Show");
        mw_show_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_show_btnActionPerformed(evt);
            }
        });
        jPanel3.add(mw_show_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 90, 40));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 255, 204));
        jButton6.setText("Progress");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, -1, 40));

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Progress In One Year");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        log___out.setBackground(new java.awt.Color(0, 0, 0));
        log___out.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log___out.setForeground(new java.awt.Color(255, 255, 204));
        log___out.setText("Log Out");
        log___out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log___outActionPerformed(evt);
            }
        });
        jPanel3.add(log___out, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 423, 80, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/table.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Progress", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1110, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/1200X700(backsteel).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered

    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited

    }//GEN-LAST:event_emailMouseExited

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void bgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseEntered

    }//GEN-LAST:event_bgMouseEntered

    private void bgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseExited

    }//GEN-LAST:event_bgMouseExited

    private void usermmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usermmMouseEntered

    }//GEN-LAST:event_usermmMouseEntered

    private void usermmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usermmMouseExited

    }//GEN-LAST:event_usermmMouseExited

    private void nidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidMouseEntered

    }//GEN-LAST:event_nidMouseEntered

    private void nidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidMouseExited

    }//GEN-LAST:event_nidMouseExited

    private void mobileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileMouseEntered

    }//GEN-LAST:event_mobileMouseEntered

    private void mobileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileMouseExited

    }//GEN-LAST:event_mobileMouseExited

    private void l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameActionPerformed

    private void passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseEntered

    }//GEN-LAST:event_passMouseEntered

    private void passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseExited

    }//GEN-LAST:event_passMouseExited

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void usermmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usermmActionPerformed

    private void log_out_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_memActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();

    }//GEN-LAST:event_log_out_memActionPerformed

    private void show_pro_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pro_memActionPerformed
        String mpa = new String(pass.getPassword());
        if (mpa.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password ", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
                String sql = "select * from member_info where  password = ?";
                PreparedStatement p = database.prepareStatement(sql);
                p.setString(1, mpa);
                ResultSet ans = p.executeQuery();
                
                if (ans.next()) {
                    
                    String fname = ans.getString("firstname");
                    String lname = ans.getString("lastname");
                    String ag = ans.getString("age");
                    String gen = ans.getString("gender");
                    String ht = ans.getString("height");
                    String wt = ans.getString("weight");
                    String bl = ans.getString("bg");
                    String mob = ans.getString("mobile");
                    String mail = ans.getString("email");
                    String nd = ans.getString("nid");
                    String us = ans.getString("username");
                    String pa = ans.getString("password");
                    String img = ans.getString("picture");
                    String gid = ans.getString("id");
                    
                    f_name.setText(fname);
                    l_name.setText(lname);
                    age.setText(ag);
                    gender.setText(gen);
                    height.setText(ht);
                    weight.setText(wt);
                    bg.setText(bl);
                    mobile.setText(mob);
                    email.setText(mail);
                    nid.setText(nd);
                    usermm.setText(us);
                    g_id.setText(gid);
                    
                    ImageIcon newimage = new ImageIcon(img);
                    pic.setIcon(newimage);
                    
                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Password or UserName", "Warning", JOptionPane.ERROR_MESSAGE);
                    pass.setText("");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_show_pro_memActionPerformed

    private void mw_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mw_idActionPerformed

    private void mw_janActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_janActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mw_janActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String mwid = mw_id.getText();
        if (mwid.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty field ", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
                String sql = "select * from member_info where  id = ?";
                PreparedStatement p = database.prepareStatement(sql);
                p.setString(1, mwid);
                ResultSet ans = p.executeQuery();
                
                if (ans.next()) {
                    
                    String mwjan = ans.getString("Jan");
                    String mwfeb = ans.getString("Feb");
                    String mwmar = ans.getString("Mar");
                    String mwap = ans.getString("April");
                    String mwmay = ans.getString("May");
                    String mwjun = ans.getString("June");
                    String mwjul = ans.getString("July");
                    String mwaug = ans.getString("Aug");
                    String mwsep = ans.getString("Sept");
                    String mwoct = ans.getString("Oct");
                    String mwnov = ans.getString("Nov");
                    String mwdec = ans.getString("Decm");
                    
                    mw_jan.setText(mwjan);
                    mw_feb.setText(mwfeb);
                    mw_mar.setText(mwmar);
                    mw_ap.setText(mwap);
                    mw_may.setText(mwmay);
                    mw_jun.setText(mwjun);
                    mw_jul.setText(mwjul);
                    mw_aug.setText(mwaug);
                    mw_sep.setText(mwsep);
                    mw_oct.setText(mwoct);
                    mw_nov.setText(mwnov);
                    mw_dec.setText(mwdec);
                    
                    flag = 1;
                    
                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Id", "Warning", JOptionPane.ERROR_MESSAGE);
                    mw_id.setText("");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mw_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_clrActionPerformed
        mw_jan.setText("");
        mw_feb.setText("");
        mw_mar.setText("");
        mw_ap.setText("");
        mw_may.setText("");
        mw_jun.setText("");
        mw_jul.setText("");
        mw_aug.setText("");
        mw_sep.setText("");
        mw_oct.setText("");
        mw_nov.setText("");
        mw_dec.setText("");

    }//GEN-LAST:event_mw_clrActionPerformed

    private void mw_up_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_up_btnActionPerformed
        
        String mwid = mw_id.getText();
        String mwjan = mw_jan.getText();
        String mwfeb = mw_feb.getText();
        String mwmar = mw_mar.getText();
        String mwap = mw_ap.getText();
        String mwmay = mw_may.getText();
        String mwjun = mw_jun.getText();
        String mwjul = mw_jul.getText();
        String mwaug = mw_aug.getText();
        String mwsep = mw_sep.getText();
        String mwoct = mw_oct.getText();
        String mwnov = mw_nov.getText();
        String mwdec = mw_dec.getText();
        
        if (mwid.equals("") || mwjan.equals("") || mwfeb.equals("") || mwmar.equals("") || mwap.equals("") || mwmay.equals("") || mwjun.equals("") || mwjul.equals("") || mwaug.equals("") || mwsep.equals("") || mwoct.equals("") || mwnov.equals("") || mwdec.equals("")) {
            JOptionPane.showMessageDialog(null, "Empty  ID ", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            
            try {
                
                Class.forName("com.mysql.jdbc.Driver");
                database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
                
                String sql = "update member_info set Jan=?, Feb=?,Mar=?,April=?,May=?,June=?,July=?,Aug=?,Sept=?,Oct=?, Nov=?,Decm=?  where id=?  ";
                
                PreparedStatement p = database.prepareStatement(sql);
                
                p.setString(1, mwjan);
                p.setString(2, mwfeb);
                p.setString(3, mwmar);
                p.setString(4, mwap);
                p.setString(5, mwmay);
                p.setString(6, mwjun);
                p.setString(7, mwjul);
                p.setString(8, mwaug);
                p.setString(9, mwsep);
                p.setString(10, mwoct);
                p.setString(11, mwnov);
                p.setString(12, mwdec);
                p.setString(13, mwid);
                
                p.executeUpdate();
                updateTable();
                button=1;
                database.close();
                JOptionPane.showMessageDialog(null, "Successfully Updated");
                
                mw_jan.setText("");
                mw_feb.setText("");
                mw_mar.setText("");
                mw_ap.setText("");
                mw_may.setText("");
                mw_jun.setText("");
                mw_jul.setText("");
                mw_aug.setText("");
                mw_sep.setText("");
                mw_oct.setText("");
                mw_nov.setText("");
                mw_dec.setText("");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        

    }//GEN-LAST:event_mw_up_btnActionPerformed

    private void mw_show_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_show_btnActionPerformed
        String mwid = mw_id.getText();
        if (mwid.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty field ", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (button == 0) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
                    String sql = "select  *from member_info where id=? ";
                    PreparedStatement p = database.prepareStatement(sql);
                    p.setString(1, mwid);
                    ResultSet ans = p.executeQuery();
                    
                    while (ans.next()) {
                        
                        String mwjan = ans.getString("Jan");
                        String mwfeb = ans.getString("Feb");
                        String mwmar = ans.getString("Mar");
                        String mwap = ans.getString("April");
                        String mwmay = ans.getString("May");
                        String mwjun = ans.getString("June");
                        String mwjul = ans.getString("July");
                        String mwaug = ans.getString("Aug");
                        String mwsep = ans.getString("Sept");
                        String mwoct = ans.getString("Oct");
                        String mwnov = ans.getString("Nov");
                        String mwdec = ans.getString("Decm");
                        
                        String tbdata[] = {mwjan, mwfeb, mwmar, mwap, mwmay, mwjun, mwjul, mwaug, mwsep, mwoct, mwnov, mwdec};
                        DefaultTableModel tm = (DefaultTableModel) mweight.getModel();
                        tm.addRow(tbdata);
                        button = 1;
                        
                    }
                    database.close();
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_mw_show_btnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String mwid = mw_id.getText();
        String mwjan = mw_jan.getText();
        String mwfeb = mw_feb.getText();
        String mwmar = mw_mar.getText();
        String mwap = mw_ap.getText();
        String mwmay = mw_may.getText();
        String mwjun = mw_jun.getText();
        String mwjul = mw_jul.getText();
        String mwaug = mw_aug.getText();
        String mwsep = mw_sep.getText();
        String mwoct = mw_oct.getText();
        String mwnov = mw_nov.getText();
        String mwdec = mw_dec.getText();
        
        if (mwid.equals("") || mwjan.equals("") || mwfeb.equals("") || mwmar.equals("") || mwap.equals("") || mwmay.equals("") || mwjun.equals("") || mwjul.equals("") || mwaug.equals("") || mwsep.equals("") || mwoct.equals("") || mwnov.equals("") || mwdec.equals("")) {
            JOptionPane.showMessageDialog(null, "Empty Field", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            
            if (flag == 1) {
                double jan = Integer.parseInt(mw_jan.getText());
                double feb = Integer.parseInt(mw_feb.getText());
                double mar = Integer.parseInt(mw_mar.getText());
                double ap = Integer.parseInt(mw_ap.getText());
                double may = Integer.parseInt(mw_may.getText());
                double jun = Integer.parseInt(mw_jun.getText());
                double jul = Integer.parseInt(mw_jul.getText());
                double aug = Integer.parseInt(mw_aug.getText());
                double sep = Integer.parseInt(mw_sep.getText());
                double oct = Integer.parseInt(mw_oct.getText());
                double nov = Integer.parseInt(mw_nov.getText());
                double dec = Integer.parseInt(mw_dec.getText());
                String name = f_name.getText();
                
                DefaultCategoryDataset barchart = new DefaultCategoryDataset();
                barchart.setValue(jan, "weight", "Jan");
                barchart.setValue(feb, "weight", "Feb");
                barchart.setValue(mar, "weight", "Mar");
                barchart.setValue(ap, "weight", "Apr");
                barchart.setValue(may, "weight", "May");
                barchart.setValue(jun, "weight", "Jun");
                barchart.setValue(jul, "weight", "July");
                barchart.setValue(aug, "weight", "Aug");
                barchart.setValue(sep, "weight", "Sep");
                barchart.setValue(oct, "weight", "oct");
                barchart.setValue(nov, "weight", "Nov");
                barchart.setValue(dec, "weight", "Dec");
                JFreeChart linechart = ChartFactory.createLineChart("Total weight change of  " + name, "Monthly", "Weight", barchart, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = linechart.getCategoryPlot();
                
                plot.setRangeGridlinePaint(Color.DARK_GRAY);
                ChartFrame frame = new ChartFrame("Progress of " + name, linechart, true);
                frame.setVisible(true);
                frame.setBounds(180, 30, 1000, 500);
                
            } else {
                
                JOptionPane.showMessageDialog(null, "Verify Your Id First", "Warning", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void log___outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log___outActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();
    }//GEN-LAST:event_log___outActionPerformed

    private void show_pro_memMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pro_memMouseEntered
        show_paa.setText("Please Enter your Password");
    }//GEN-LAST:event_show_pro_memMouseEntered

    private void show_pro_memMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pro_memMouseExited
        show_paa.setText("");
    }//GEN-LAST:event_show_pro_memMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField bg;
    private javax.swing.JTextField email;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField g_id;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField l_name;
    private javax.swing.JButton log___out;
    private javax.swing.JButton log_out_mem;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField mw_ap;
    private javax.swing.JTextField mw_aug;
    private javax.swing.JButton mw_clr;
    private javax.swing.JTextField mw_dec;
    private javax.swing.JTextField mw_feb;
    private javax.swing.JTextField mw_id;
    private javax.swing.JTextField mw_jan;
    private javax.swing.JTextField mw_jul;
    private javax.swing.JTextField mw_jun;
    private javax.swing.JTextField mw_mar;
    private javax.swing.JTextField mw_may;
    private javax.swing.JTextField mw_nov;
    private javax.swing.JTextField mw_oct;
    private javax.swing.JTextField mw_sep;
    private javax.swing.JButton mw_show_btn;
    private javax.swing.JButton mw_up_btn;
    private javax.swing.JTable mweight;
    private javax.swing.JTextField nid;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel show_paa;
    private javax.swing.JButton show_pro_mem;
    private javax.swing.JTextField usermm;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
