/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_trial;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Package extends javax.swing.JFrame {

    /**
     * Creates new form Package
     */
    public Package() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JEditorPane();
        combo = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        web = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Packages");
        setBounds(new java.awt.Rectangle(300, 150, 700, 550));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Packages");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 350, 70));

        pane.setEditable(false);
        pane.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(pane);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 350, 250));

        combo.setBackground(new java.awt.Color(255, 51, 51));
        combo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Happy Member", "Super Saver", "Elite Member", "Holiday Member", "Female Member" }));
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboMouseExited(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 50));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("<<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 110, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contact :01727778867");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 280, 30));

        web.setBackground(new java.awt.Color(0, 0, 0));
        web.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        web.setForeground(new java.awt.Color(204, 204, 255));
        web.setText("Visit Website");
        web.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webMouseExited(evt);
            }
        });
        web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webActionPerformed(evt);
            }
        });
        getContentPane().add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 130, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Live Chat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/700X550(bg_pack).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

        if (combo.getSelectedIndex() == 0) {
            pane.setText("Gym hour: 7.00 am-5.00 pm " + "\n" + "Monthly Fee: 1200" + "\n" + "Admission Fee: 2000" + "\n" + "Locker, Treadmill, Cycle available\n\n" + "**ADVANCE PAYMENT DISCOUNTS** \n \n"
                    + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                    + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                    + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
        } else if (combo.getSelectedIndex() == 1) {
            pane.setText("Gym hour: 7.00 am-11.00 pm " + "\n" + "Monthly Fee: 1500" + "\n" + "Admission Fee: 2000" + "\n" + "Locker, Treadmill, Cycle available\n\n" + "**ADVANCE PAYMENT DISCOUNTS** \n \n"
                    + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                    + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                    + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
        } else if (combo.getSelectedIndex() == 2) {
            pane.setText("Gym hour: 7.00 am-11.00 pm " + "\n" + "Monthly Fee: 2000" + "\n" + "Admission Fee: 2000" + "\n" + "Locker, Treadmill, Cycle available,4 Steam bath every month, Shower facility\n\n" + "**ADVANCE PAYMENT DISCOUNTS** \n \n"
                    + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                    + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                    + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
        } else if (combo.getSelectedIndex() == 3) {
            pane.setText("Gym hour: 7.00 am-5.00 pm (only can workout Friday and Saturday)" + "\n" + "Monthly Fee: 1200" + "\n" + "Admission Fee: 2000" + "\n" + "Locker, Treadmill, Cycle available\n\n" + "**ADVANCE PAYMENT DISCOUNTS** \n \n"
                    + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                    + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                    + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
        } else {
            pane.setText("Gym hour: 7.00 am-10.00 pm\n" + "Monthly Fee: 1200\n" + "Admission Fee: 2000\n" + "Locker, Treadmill, Cycle available\n\n" + "**ADVANCE PAYMENT DISCOUNTS** \n \n"
                    + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                    + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                    + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
        }
    }//GEN-LAST:event_comboActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Choose1 c = new Choose1();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webActionPerformed
        Desktop browser = Desktop.getDesktop();
        try {
            browser.browse(new URI("http://www.kazisgym.com/"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_webActionPerformed

    private void comboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseEntered
        pane.setText("");
    }//GEN-LAST:event_comboMouseEntered

    private void comboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseExited
        pane.setText("\n\n\n\n\n                     ***ADVANCE PAYMENT DISCOUNTS*** \n \n"
                + "OFFER 01: PAY FOR 3 MONTHS and GET 10% DISCOUNT \n"
                + "OFFER 02: PAY FOR 6 MONTHS and GET 20% DISCOUNT \n"
                + "OFFER 03: PAY FOR 12 MONTHS and GET 30% DISCOUNT \n");
    }//GEN-LAST:event_comboMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Chat_Stranger cs = new Chat_Stranger();
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setForeground(Color.white);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setForeground(Color.red);
    }//GEN-LAST:event_backMouseExited

    private void webMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMouseEntered
        web.setForeground(Color.BLUE);
    }//GEN-LAST:event_webMouseEntered

    private void webMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMouseExited
        web.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_webMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Package().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane pane;
    private javax.swing.JButton web;
    // End of variables declaration//GEN-END:variables
}
