/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_trial;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class MemberLog extends javax.swing.JFrame {

    /**
     * Creates new form MemberLog
     */
    public MemberLog() {
        initComponents();
    }
    public Connection database;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        muserName = new javax.swing.JTextField();
        mpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Mmeber_logbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Login");
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 53, 222, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 170, -1, 38));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 235, -1, -1));

        muserName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        muserName.setToolTipText("");
        getContentPane().add(muserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 170, 226, 38));

        mpass.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpassActionPerformed(evt);
            }
        });
        getContentPane().add(mpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 232, 226, -1));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Forgotten Password?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 356, -1, -1));

        Mmeber_logbtn.setBackground(new java.awt.Color(204, 255, 204));
        Mmeber_logbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Mmeber_logbtn.setText("Login");
        Mmeber_logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mmeber_logbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Mmeber_logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 282, 202, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("<<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 40));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Reset");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 376, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_trial/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login log =new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Mmeber_logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mmeber_logbtnActionPerformed
        String muser=muserName.getText();
        String mpa=new String(mpass.getPassword());
         if (muser.equals("") || mpa.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            database = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/kazi_gym", "root", "");
            String sql = "select * from member_info where username = ? and password = ?";
            PreparedStatement p = database.prepareStatement(sql);
            p.setString(1, muser);
            p.setString(2, mpa);
            ResultSet ans = p.executeQuery();

            if (ans.next()) {
                dispose();
                MemberMain mmp = new MemberMain();
                mmp.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, " Invalid Password or UserName", "Warning", JOptionPane.ERROR_MESSAGE);
                muserName.setText("");
                mpass.setText("");
            }
            database.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Mmeber_logbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Member_Reset mdr=new Member_Reset();
        mdr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mmeber_logbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField mpass;
    private javax.swing.JTextField muserName;
    // End of variables declaration//GEN-END:variables
}
